#' Set Graph
#' 
#' Sets ups page for a specific grtaph
#' 
#' 
#' @param graphNum the number of the graph.
#' @param layout the layout of the graph.
#' @param noTicks suppress ticks on a specific axis.
#' @return The parameters of the margin of the plot area.
#' @note This function is called using the information generated by
#' \code{setLayout}. It invisibly sets up the graphics device for the next
#' graph.
#' @seealso \code{\link{setLayout}}
#' @keywords dplot
#' @export setGraph
setGraph <- function(graphNum, layout, noTicks=NULL) {
	# Coding History:
	#    2008Jun27 DLLorenz Original coding.
	#    2010Nov30 DLLorenz Modified for R
	#    2011Oct24 DLLorenz Tweaks for package
	#    2014Jun26 DLLorenz Converted to roxygen.
	#
  par(fig=layout[[graphNum]]$fig)
  margin <- layout[[graphNum]]$margin
  ## this code protects against NAs
  if(!is.null(noTicks))
    margin[noTicks] <- ifelse(margin[noTicks] == 0, -101, -margin[noTicks])
  par(new=TRUE)
  invisible(margin)
}
